version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - echo Installing dependencies...
      - pip install --upgrade pip
      - pip install cfn-lint taskcat

  build:
    commands:
      - echo Running CloudFormation lint...

      - cfn-lint ../main.yaml

      - cfn-lint ../templates/*.yaml

      - echo Running TaskCat validation...

      - cd ..
      - taskcat test run -c codepipeline/taskcat.yml

artifacts:
  files:
    - '**/*'
