project:
name: nt548-q22-cloudformation

tests:
dev:
template: ./main.yaml

```
regions:
  - ap-southeast-1

parameters:
  ProjectName: nt548-q22
  Environment: dev

  TemplateUrlVpc: https://nt548-q22-cfn-templates.s3.ap-southeast-1.amazonaws.com/templates/vpc.yaml

  TemplateUrlEc2: https://nt548-q22-cfn-templates.s3.ap-southeast-1.amazonaws.com/templates/ec2.yaml
```
